# Generated by Django 3.2.16 on 2023-01-13 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='catergory',
            new_name='category',
        ),
    ]
