# Generated by Django 3.2.16 on 2023-01-17 10:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_rename_catergory_room_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
