# Generated by Django 3.2.16 on 2023-01-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_room_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('LUX', 'LUXURY'), ('DUB', 'DUBBLE'), ('SIN', 'SINGAL')], max_length=3),
        ),
    ]
